AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/*_helper.rb'
    - 'spec/support/database_cleaner.rb'
    - 'Gemfile*'
Metrics/BlockLength:
 Enabled: true
 Exclude: 
    - 'spec/**/*'
    - 'app/admin/**/*'
Metrics/MethodLength:
  Max: 20
Style/ClassAndModuleChildren:
  Enabled: false