##
# Allow more secure way of handling credentials as environmental variables
#
# $ echo "export USERNAME=username" >> ~/.profile
#
# $ echo "export PASSWORD=password" >> ~/.profile

# database.yml
default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  #database: grendada_database_development
  database: app_development

test:
  #database: grendada_database_test
  database: app_test

production:
  #database: grendada_database_production
  database: app_production
